services:
  db:
    image: postgres:18
    container_name: django-landing-db
    environment:
      POSTGRES_DB: django_landing
      POSTGRES_PASSWORD: django_landing
      POSTGRES_USER: django_landing
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
    ports:
      - "${DATABASE_EXTERNAL_PORT}:${DATABASE_PORT}"
    networks:
      - django-landing-network

  app:
    container_name: django-landing-app
    build:
      context: .
    volumes:
      - ./:/app
#    expose:
#      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migrations
    networks:
      - django-landing-network

  migrations:
    container_name: django-landing-migrations
    build:
      context: .
    command: ["python", "manage.py", "migrate", "--no-input"]
    restart: "no"
    depends_on:
      - db
    volumes:
      - ./:/app
    networks:
      - django-landing-network

volumes:
  portainer_data:

networks:
  django-landing-network:
    driver: bridge