services:
  db:
    image: postgres:18
    container_name: django-landing-db
    environment:
      POSTGRES_DB: django_landing
      POSTGRES_PASSWORD: django_landing
      POSTGRES_USER: django_landing
    ports:
      - "5432:5432"

  app:
    container_name: django-landing-app
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - migrations

  migrations:
    container_name: django-landing-migrations
    build:
      context: .
    command: ["python", "manage.py", "migrate", "--no-input"]
    restart: "no"
    depends_on:
      - db
    volumes:
      - ./:/app
