# Generated by Django 5.2.6 on 2025-10-04 17:40

import django.db.models.deletion
import landing.models
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('template', models.CharField(default='templates/landing_basic.html', max_length=255)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('css_files', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PageElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('header', 'Header (h1-h6)'), ('text', 'Text/Paragraph'), ('image', 'Image'), ('container', 'Simple Container'), ('grid', 'Grid Container'), ('card', 'Card/Block'), ('list', 'List (ul/ol)'), ('button', 'Button/Link'), ('section', 'Section')], max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('html_attrs', models.JSONField(blank=True, default=dict)),
                ('image', models.ImageField(blank=True, null=True, upload_to=landing.models.page_image_upload_to)),
                ('css_classes', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='landing.page')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='landing.pageelement')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
